site_name: VPX Game Logic Framework
site_url: https://mpcarr.github.io/vpx-gle-framework/
site_author: flux
site_description: A Visual Pinball X framework for creating pinball game logic and rules using Visual Basic Script
# Repository
repo_name: mpcarr/vpx-gle-framework
repo_url: https://github.com/mpcarr/vpx-gle-framework


nav:
  - 'Getting Started':
    - 'Installation': installing.md
    - 'Tutorial':
      - 'Trough': 'tutorial/tutorial-trough.md'
      - 'Plunger': 'tutorial/tutorial-plunger.md'
      - 'Flippers': 'tutorial/tutorial-flippers.md'
      - 'Auto Fire Devices': 'tutorial/tutorial-autofire.md'
      - 'Lights': 'tutorial/tutorial-lights.md'
      - 'Ball Devices': 'tutorial/tutorial-ball-devices.md'
      - 'Ball Save': 'tutorial/tutorial-ballsave.md'
      - 'Scoring': 'tutorial/tutorial-scoring.md'
      - 'Shots': 'tutorial/tutorial-shots.md'
      - 'Event Player': 'tutorial/tutorial-event-player.md'
      - 'Timer': 'tutorial/tutorial-timer.md'
      #- 'Shows': 'tutorial/tutorial-shows.md'
  #- 'Features': features.md
  - 'Game Logic':
    - Virtual Devices:
          - 'Auto Fire Device': autofire.md
          - 'Ball Device': ball-device.md
          - 'Diverter': diverter.md
          - 'Drop Target': drop-target.md
          - 'Flipper': flipper.md
          - 'Magnet': magnet.md
    - Modes:
          - 'Ball Save': ball-save.md
          - 'Combo Switches': combo-switches.md
          - 'DOF Player': dof-player-config.md
          - 'Event Player': event-player.md
          - 'Extra Ball': extra-ball.md
          - 'High Score': high-score.md
          - 'Light Player': light-player.md
          - 'Modes': mode.md
          - 'Multiball': multiball.md
          - 'Multiball Locks': multiball-locks.md
          - 'Queue Event Player': queue-event-player.md
          - 'Random Event Player': random-event-player.md
          - 'Shot': shot.md
          - 'Shot Group': shot-group.md
          - 'Shot Profile': shot-profile.md
          - 'Sequence Shot': sequence-shot.md
          - 'Show Player': show-player.md
          - 'Slide Player': slide-player.md
          - 'Sound Player': sound-player.md
          - 'State Machine': state-machine.md
          - 'Timer': timer.md
          - 'Timed Switches': timed-switches.md
          - 'Tilt': tilt.md
          - 'Variable Player': variable-player.md

    #- 'Events System': events.md
    #- 'Player State': player-state.md
  #- 'Light Controller': light-controller.md
  #- 'DMD / LCD': dmd-lcd.md
  - About: about.md
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - toc:                    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#table-of-contents
      title: On this page
  - attr_list