site_name: VPX Game Logic Framework
site_url: https://mpcarr.github.io/vpx-gle-framework/
nav:
  - 'Getting Started':
    - 'Installation': installing.md
    - 'Tutorial':
      - 'Trough': 'tutorial/tutorial-trough.md'
      - 'Plunger': 'tutorial/tutorial-plunger.md'
      #- 'Ball Save': 'tutorial/tutorial-ballsave.md'
      - 'Lights': 'tutorial/tutorial-lights.md'
      #- 'Shows': 'tutorial/tutorial-shows.md'
  #- 'Features': features.md
  #- 'Game Logic':
    #- Virtual Devices:
    #      - 'Ball Device': ball-device.md
    #      - 'Diverter': diverter.md
    #      - 'Drop Target': drop-target.md
    #- 'Game Logic Commands':
    #      - 'Ball Save': ball-save.md
    #      - 'Counter': counter.md
    #      - 'Event Player': event-player.md
    #      - 'Light Player': light-player.md
    #      - 'Mode': mode.md
    #      - 'Multiball Locks': multiball-locks.md
    #      - 'Multiball': multiball.md
    #      - 'Show Player': show-player.md
    #      - 'Timer': timer.md
    #- 'Events System': events.md
    #- 'Player State': player-state.md
  #- 'Light Controller': light-controller.md
  #- 'DMD / LCD': dmd-lcd.md
  - About: about.md
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - toc:                    # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#table-of-contents
      title: On this page
  - attr_list